version: '3.8'  # Updated to 3.8 for better Traefik compatibility

services:
  activepieces:
    image: ghcr.io/activepieces/activepieces:0.50.0
    container_name: activepieces
    restart: unless-stopped
    networks:
      - activepieces
      - dokploy-network
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - ./cache:/usr/src/app/cache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.activepieces.rule=Host(`activepieces.yourdomain.com`)"
      - "traefik.http.routers.activepieces.entrypoints=web"
      - "traefik.http.routers.activepieces-secure.entrypoints=websecure"
      - "traefik.http.routers.activepieces-secure.rule=Host(`activepieces.yourdomain.com`)"
      - "traefik.http.routers.activepieces-secure.tls=true"
      - "traefik.http.routers.activepieces-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.activepieces.loadbalancer.server.port=80"
      - "traefik.docker.network=dokploy-network"

  postgres:
    image: postgres:14.4
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${AP_POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}
      - POSTGRES_USER=${AP_POSTGRES_USERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - activepieces

  redis:
    image: redis:7.0.7
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - activepieces

volumes:
  postgres_data:
  redis_data:

networks:
  activepieces:
    driver: bridge
  dokploy-network:
    external: true
